#!/bin/sh

### Package: mix-install-xserver-xorg
### Version: v0.20260219.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=main
fi

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR="/usr/local"
fi

# BUILDTYPE
if [ -z $BUILDTYPE ]; then
 BUILDTYPE="release"
fi

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://gitlab.freedesktop.org
GITREPO=xorg
GITTREE=xserver
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR="`gcc -dumpmachine`"

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep xserver-xorg xserver-xorg-dev
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 libxcb-sync-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -f
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson setup tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --buildtype="$BUILDTYPE"

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
