#!/bin/sh

### Package: mix-install-hdr10plus
### Version: v0.20250916.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
# Upstream branch is "main".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH=main
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="quietvoid"
GITTREE="hdr10plus_tool"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git \
 fontconfig
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## CLEAN
if [ -d "$DEVDIR/$PKGDIR" ]; then
 sudo rm -Rf "$DEVDIR/$PKGDIR/target"
 sudo rm -Rf "$DEVDIR/$PKGDIR/hdr10plus/target"
 sudo rm -Rf "$DEVDIR/$PKGDIR/hdr10plus/tmpbuild"
fi

## GIT
[ -d "$PKGDIR" ] || git clone --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

git submodule update --init

## LIB BUILD
cd "$DEVDIR/$PKGDIR/hdr10plus"
cargo cinstall --release --destdir=tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR"

## LIB INSTALL
sudo cp -a tmpbuild/* /
sudo ldconfig

## TOOL BUILD
cd "$DEVDIR/$PKGDIR"
cargo build --release

# TOOL INSTALL
sudo install -D -m 755 "target/release/hdr10plus_tool" "$DESTDIR/bin/hdr10plus_tool"
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
