#!/bin/sh

### Package: mix-install-wireplumber
### Version: v0.20250503.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: pipewire

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# Upstream branch is "master"
if [ -z $GITBRANCH ]; then
 GITBRANCH=0.4
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## VARS
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://gitlab.freedesktop.org
GITREPO=pipewire
GITTREE=wireplumber
PKGDIR=$GITTREE\_$GITBRANCH

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
# sudo apt-get -y build-dep pipewire
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 libbluetooth-dev libsdl2-dev libjack-jackd2-dev libcamera-dev \
 libldacbt-enc-dev libldacbt-abr-dev libopenaptx-dev libfdk-aac-dev \
 libavcodec-dev
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard HEAD
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson setup tmpbuild --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --buildtype=release \
-Dsystem-lua=true -Ddoc=disabled

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
