#!/bin/sh

### Package: mix-install-xkbcommon
### Version: v0.20250511.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
 PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

# GITBRANCH
# Upstream branch is "master"
if [ -z $GITBRANCH ]; then
 GITBRANCH=master
fi
echo "*** GITBRANCH selected is $GITBRANCH."

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi
echo "*** DESTDIR selected is $DESTDIR."

## VARS
DEVDIR=$MIXTOOLSDIR/upstream
RESDIR=$MIXTOOLSDIR/resources
GITURL=https://github.com
GITREPO=xkbcommon
GITTREE=libxkbcommon
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
# sudo apt-get -y build-dep pipewire
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --recursive --depth=1 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard HEAD
git pull
git submodule update --init --recursive --depth=1

## CLEAN
rm -Rf tmpbuild

## CONFIGURE
meson setup tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --buildtype=release

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
