#!/bin/bash

### Package: mix-install-xwayland
### Version: v0.20250916.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)
### Script Conflicts: xserver-xorg

## ENVIRONMENT
# MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR":"$PATH"
fi

# VARIABLES
GITBRANCH="xwayland-24.1"
GITURL="https://gitlab.freedesktop.org"
GITREPO="xorg"
GITTREE="xserver"

source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-environment"

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep xwayland
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 libaudit-dev libbsd-dev libcap-ng-dev libdmx-dev libdmx1 \
 libfontenc-dev libgbm-dev libgcrypt20-dev libmd-dev \
 libxaw7-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev \
 libxcb-render-util0-dev libxcb-util-dev libxcb-util0-dev libxcb-xf86dri0 \
 libxcb-xf86dri0-dev libxcb-xkb-dev libxcb-xv0 libxcb-xv0-dev libxfont-dev \
 libxfont2 libxkbfile-dev libxmu-dev libxmu-headers libxmuu-dev libxpm-dev \
 libxres-dev libxres1 libxkbcommon-dev x11-apps libtirpc-dev \
 libei-dev liboeffis-dev fop
fi

# PREP
source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-prep"

## CLEAN
source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-clean-tmpbuild"

## GIT
source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-git"

## GITPR
source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-git-pr"

## CONFIGURE
source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-configure-meson"

## BUILD
source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-build-ninja"

## INSTALL
source "$MIXTOOLSDIR/resources/mix-tools/mix-resources-install-ninja"

## EXIT
echo "*** Done."
exit

## ENJOY
