#!/bin/sh

### Package: mix-install-rustup
### Version: v0.20250928.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

echo "*** Uninstalling rustc, cargo, and rustup if installed."
## UNINSTALL DEBIAN PACKAGES
if [ "$INSTALLDEPS" = debian ]; then
 sudo apt-get -y --purge remove rustc cargo rustup
 sudo apt-get -y autoremove
fi

## INSTALL
echo "*** Installing rustup for user."
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh \
-s -- -q -y --default-toolchain nightly

## CONFIGURE
#rustup set profile complete
rustup set profile default
rustup set auto-self-update enable
rustup set auto-install enable
rustup toolchain install stable
rustup toolchain install nightly
rustup component add rust-src
rustup default nightly

## EXIT
echo "*** Done."
exit

## ENJOY
