#!/bin/sh

### Package: mix-install-mesa
### Version: v0.20260219.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="main"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## GITPR
if [ -z "$GITPR" ]; then
 GITPR="none"
fi
echo "*** GITPR selected is $GITPR."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## GALLIUMDRIVERS
if [ -z "$GALLIUMDRIVERS" ];then
 GALLIUMDRIVERS="radeonsi,zink,llvmpipe,softpipe"
fi
echo "*** GALLIUMDRIVERS selected is $GALLIUMDRIVERS."

## RUSTICLDRIVERS
if [ -z "$RUSTICLDRIVERS" ];then
 RUSTICLDRIVERS="radeonsi"
fi
echo "*** RUSTICLDRIVERS selected is $RUSTICLDRIVERS."

## VULKANDRIVERS
if [ -z "$VULKANDRIVERS" ];then
 VULKANDRIVERS="amd,swrast"
fi
echo "*** VULKANDRIVERS selected is $VULKANDRIVERS."

## VULKANLAYERS
if [ -z "$VULKANLAYERS" ];then
 VULKANLAYERS="device-select,overlay,screenshot,anti-lag,vram-report-limit"
fi
echo "*** VULKANLAYERS selected is $VULKANLAYERS."

## TOOLS
if [ -z "$TOOLS" ];then
 TOOLS="drm-shim,glsl,zink"
fi
echo "*** TOOLS selected is $TOOLS."

## LLVMVER
# options are 22, 21, 20, 19, or local
if [ -z "$LLVMVER" ];then
 LLVMVER="22"
fi
echo "*** LLVMVER selected is $LLVMVER."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://gitlab.freedesktop.org"
GITREPO="mesa"
GITTREE="mesa"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 libunwind-dev libxvmc-dev libxv-dev libxcb-xinput-dev libxcb-damage0-dev \
 libvdpau-dev python3-mako bison byacc flex libxcb-glx0-dev \
 libxcb-dri2-0-dev libxcb-dri3-dev directx-headers-dev flex glslang-tools \
 libsensors-dev libset-scalar-perl libvdpau-dev libxcb-dri2-0-dev libxcb-present-dev \
 libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev \
 libxshmfence-dev spirv-tools libclc-20-dev libelf-dev libx11-xcb-dev \
 directx-headers-dev dwz ed gettext glslang-tools groff-base \
 intltool-debian libarchive-zip-perl libelf-dev libfile-stripnondeterminism-perl \
 libglvnd-core-dev libglvnd-dev libopengl-dev libopengl0 \
 libsensors-dev libset-scalar-perl libsub-override-perl \
 libuchardet0 libvdpau-dev libvdpau1 libvulkan-dev \
 libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev \
 libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev \
 libxrandr-dev libxshmfence-dev libxxf86vm-dev libzstd-dev \
 man-db python3-mako python3-markupsafe quilt spirv-tools bindgen \
 libclang-cpp20-dev lua5.4 liblua5.4-dev
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## CLEAN
sudo rm -Rf "$PKGDIR/tmpbuild"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=100

## GITPR
if [ "$GITPR" != "none" ]; then
 git pull origin pull/$GITPR/head
fi

## WORKAROUNDS
cp "$RESDIR/mesa/custom-llvm-$LLVMVER.ini" .
cp "$RESDIR/mesa/clangd" .clangd

## CONFIGURE
meson setup tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --buildtype="$BUILDTYPE" \
-Dgallium-drivers="$GALLIUMDRIVERS" -Dgallium-extra-hud=true \
-Dgallium-rusticl=true -Dgallium-rusticl-enable-drivers="$RUSTICLDRIVERS" \
-Dvulkan-drivers="$VULKANDRIVERS" -Dvulkan-layers="$VULKANLAYERS" -Dspirv-to-dxil=true \
-Dbuild-tests=false -Dtools="$TOOLS" -Dteflon=true -Dvulkan-beta=true -Dvideo-codecs=all \
-Drust_std=2021 --native-file="custom-llvm-$LLVMVER.ini"

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
