#!/bin/sh

### Package: mix-install-opus
### Version: v0.20250916.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### VARIABLES
# MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="main"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## TMPDIR
if [ -z "$TMPDIR" ]; then
 TMPDIR="/tmp/mix-tools"
fi
echo "*** TMPDIR selected is $TMPDIR."

## OPUSDATAFILE
if [ -z "$OPUSDATAFILE" ]; then
 OPUSDATAFILE="opus_data-4ec556dd87e63c17c4a805c40685ef3fe1fad7c8b26b123f2ede553b50158cb1.tar.gz"
fi
echo "*** OPUSDATAFILE selected is $OPUSDATAFILE."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="xiph"
GITTREE="opus"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

### INSTALLDEPS
# Debian
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p "$DEVDIR"
mkdir -p "$TMPDIR/$PKGDIR"
cd "$DEVDIR"

## OPUSDATAFILE COPY TO DEVDIR
if [ -f "$DEVDIR/$PKGDIR/$OPUSDATAFILE" -a ! -f "$DEVDIR/$OPUSDATAFILE" ]; then
 cp "$DEVDIR/$PKGDIR/$OPUSDATAFILE" "$DEVDIR/"
fi

## GIT
[ -d "$PKGDIR" ] || git clone --depth=1000 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

## OPUSDATAFILE COPY TO PKGDIR
if [ -f "$DEVDIR/$OPUSDATAFILE" -a ! -f "$DEVDIR/$PKGDIR/$OPUSDATAFILE" ]; then
 cp "$DEVDIR/$OPUSDATAFILE" "$DEVDIR/$PKGDIR/"
fi

## PACKAGE_VERSION
PACKAGEVERSION="`git describe --always | sed -e 's|v||' -e 's|-|.|g' -e 's|draft.ietf.codec.oggopus.||'`"
echo "PACKAGE_VERSION=$PACKAGEVERSION" > package_version

## CONFIGURE
./autogen.sh
./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" \
--enable-custom-modes --enable-dred --enable-deep-plc --enable-lossgen \
--enable-osce-training-data --enable-osce --enable-maintainer-mode

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## OPUSDATAFILE COPY TO DEVDIR
if [ -f "$DEVDIR/$PKGDIR/$OPUSDATAFILE" -a ! -f "$DEVDIR/$OPUSDATAFILE" ]; then
 cp "$DEVDIR/$PKGDIR/$OPUSDATAFILE" "$DEVDIR/"
fi

## EXIT
exit

## ENJOY
