#!/bin/sh

### Package: mix-install-vapoursynth-autocrop
### Version: v0.20250928.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
# Upstream branch is "master".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="master"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## VAPOURSYNTHDIR
if [ -z "$VAPOURSYNTHINCLUDEDIR" ]; then
 VAPOURSYNTHINCLUDEDIR="/usr/local/include/vapoursynth"
fi
echo "*** VAPOURSYNTHINCLUDEDIR selected is $VAPOURSYNTHINCLUDEDIR."

## TMPDIR
if [ -z "$TMPDIR" ]; then
 TMPDIR="/tmp/mix-tools"
fi
echo "*** TMPDIR selected is $TMPDIR."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="irrational-encoding-wizardry"
GITTREE="vapoursynth-autocrop"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## GIT
[ -d "$PKGDIR" ] || git clone --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

## BUILD
"$CXX" -I"$VAPOURSYNTHINCLUDEDIR" -std=c++11 -shared -fPIC -O2 autocrop.cpp -o libautocrop.so

## INSTALL
sudo install -D -m 755 libautocrop.so "$DESTDIR/lib/$MULTILIBDIR/vapoursynth/libautocrop.so"

## EXIT
echo "*** Done."
exit

## ENJOY
