#!/bin/sh

### Package: mix-install-handbrake-svt-av1-psy
### Version: v0.20250601.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: pipewire

### OVERRIDES

## MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "master".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="main"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="nj0be"
GITTREE="handbrake-svt-av1-psy"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## CLEAN
sudo rm -Rf "$PKGDIR/tmpbuild"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --depth=100

## CONFIGURE
meson setup tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --buildtype="$BUILDTYPE"

## PATCH
./patch.sh -c

## CONFIGURE
cd HandBrake
./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" \
--enable-gtk3 --enable-x265 --enable-numa --enable-fdk-aac --enable-nvenc --enable-nvdec \
--enable-qsv --enable-vce

## BUILD
cd build
make -j `nproc`

## INSTALL
sudo make install
[ -f "$DESTDIR/bin/handbrake-gtk" ] || sudo ln -s "$DESTDIR/bin/ghb" "$DESTDIR/bin/handbrake-gtk"
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
