#!/bin/sh

### Package: mix-install-cargo-c
### Version: v0.20250928.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "master". Tag format is v#.#.#.
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="master"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## COMPILEROVERRIDE
if [ -z "$COMPILEROVERRIDE" ]; then
 COMPILEROVERRIDE="true"
fi
echo "*** COMPILEROVERRIDE selected is $COMPILEROVERRIDE."
if [ "$COMPILEROVERRIDE" = "true" ]; then
 CFLAGS="$CFLAGSNOLTO"
 CXXFLAGS="$CXXFLAGSNOLTO"
 CPPFLAGS="$CPPFLAGSNOLTO"
fi

## VARS
DEVDIR="$MIXTOOLSDIR/upstream"
RESDIR="$MIXTOOLSDIR/resources"
GITURL="https://github.com"
GITREPO="lu-zero"
GITTREE="cargo-c"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=100

## BUILD
cargo build --"$BUILDTYPE"

## INSTALL
cargo install --all-features --path .

## EXIT
echo "*** Done."
exit

# ENJOY
