#!/bin/sh

### Package: mix-install-libdvdnav
### Version: v0.20260102.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "master".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="master"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## PKGVER
# Options are 6 or 7, to select gmake (6) or meson (7) build
if [ -z "$PKGVER" ]; then
 PKGVER="7"
fi
echo "*** PKGVER selected is $PKGVER."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://code.videolan.org"
GITREPO="videolan"
GITTREE="libdvdnav"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y build-dep libdvdnav-dev
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## CLEAN
sudo rm -Rf "$PKGDIR/tmpbuild"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --depth=100

## CONFIGURE
# 6
if [ "$PKGVER" = "6" ]; then
 autoreconf -vifs
 ./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR"
fi
# 7
if [ "$PKGVER" = "7" ]; then
 meson setup tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --buildtype="$BUILDTYPE"
fi

## BUILD
# 6
if [ "$PKGVER" = "6" ]; then
 make -j `nproc`
fi
# 7
if [ "$PKGVER" = "7" ]; then
 ninja -C tmpbuild
fi

## INSTALL
# 6
if [ "$PKGVER" = "6" ]; then
 sudo make install
fi
# 7
if [ "$PKGVER" = "7" ]; then
 sudo ninja -C tmpbuild install
fi
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
