#!/bin/sh

### Package: mix-install-x264-tmod
### Version: v20250215.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLS
if [ -z $MIXTOOLSDIR ]; then
 MIXTOOLSDIR="`pwd`"
fi

# INSTALLDEPS
if [ -z $INSTALLDEPS ]; then
 INSTALLDEPS=debian
fi

# GITBRANCH
if [ -z $GITBRANCH ]; then
 GITBRANCH=t_mod_New
fi

# DESTDIR
if [ -z $DESTDIR ]; then
 DESTDIR=/usr/local
fi

## VARS
RESDIR=$MIXTOOLSDIR/resources
DEVDIR=$MIXTOOLSDIR/upstream
GITURL=https://github.com
GITREPO=jpsdr
GITTREE=x264
PKGDIR=$GITTREE\_$GITBRANCH
MULTILIBDIR=`gcc -dumpmachine`

## INSTALLDEPS
# Debian Dependencies
if [ $INSTALLDEPS = debian ]; then
 sudo apt-get -y build-dep x264
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p $DEVDIR
cd $DEVDIR

## GIT
[ -d $PKGDIR ] || git clone --depth=200 $GITURL/$GITREPO/$GITTREE.git --branch=$GITBRANCH $PKGDIR
cd $PKGDIR
git clean -dfx
git reset --hard
git pull
git submodule init
git submodule update

## CONFIGURE
./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" \
--enable-shared --enable-bashcompletion --enable-lto --enable-pic \
--enable-nonfree --bit-depth=all --chroma-format=all \
--disable-audio --disable-qtaac --disable-faac --disable-mp3 --disable-lavc --disable-avi-output \
--disable-lsmash --enable-opencl

#--disable-avs --disable-swscale --disable-lavf --disable-ffms --disable-gpac --disable-lsmash

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
exit

## ENJOY
