#!/bin/sh

### Package: mix-install-nasm
### Version: v0.20251120.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: wlroots wayland wayland-protocols

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
# Upstream branch is "master".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="master"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## TMPDIR
if [ -z "$TMPDIR" ]; then
 TMPDIR="/tmp/mix-tools"
fi
echo "*** TMPDIR selected is $TMPDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## COMPILEROVERRIDE
# Broken with ccache
# Default
if [ -z "$COMPILEROVERRIDE" ]; then
 COMPILEROVERRIDE="ON"
fi
# Check
if [ "$COMPILEROVERRIDE" = "ON" ]; then
 CC="$CCNOCCACHE"
 CPP="$CPPNOCCACHE"
 CXX="$CXXNOCCACHE"
 CFLAGS="$CFLAGSNOLTO"
 CPPFLAGS="$CPPFLAGSNOLTO"
 CXXFLAGS="$CXXFLAGSNOLTO"
 LD=""
 LDFLAGS=""
else
 COMPILEROVERRIDE="OFF"
fi
echo "*** COMPILEROVERRIDE selected is $COMPILEROVERRIDE."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="netwide-assembler"
GITTREE="nasm"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

### INSTALLDEPS
# Debian
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y build-dep nasm
 sudo apt-get -y install build-essential coreutils libc-bin git cmake
fi

## PREP
set -e
mkdir -p "$DEVDIR"
mkdir -p "$TMPDIR/$PKGDIR"
cd "$DEVDIR"

## CLEAN
sudo rm -Rf "$PKGDIR/tmpbuild"

## GIT
[ -d "$PKGDIR" ] || git clone --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

## CONFIGURE
./autogen.sh
./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR"

## BUILD
make -j `nproc` manpages
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
