#!/bin/sh

### Package: mix-install-v4l-utils
### Version: v0.20260117.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "master".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="master"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://git.linuxtv.org"
GITREPO="v4l-utils"
GITTREE="v4l-utils"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y build-dep v4l-utils
 sudo apt-get -y install build-essential coreutils libc-bin git meson
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## CLEAN
sudo rm -Rf "$PKGDIR/tmpbuild"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=100 "$GITURL/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --depth=100

## CONFIGURE
meson setup tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --buildtype="$BUILDTYPE"

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
