#!/bin/sh

### Package: mix-install-zig
### Version: v0.20251230.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "master". Releases are tagged "#.#.#".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="0.15.2"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## LLVMVER
if [ -z "$LLVMVER" ]; then
 LLVMVER="22"
fi
echo "*** LLVMVER selected is $LLVMVER."

## COMPILEROVERRIDE
# Broken with lto and mold
if [ -z "$COMPILEROVERRIDE" ]; then
 COMPILEROVERRIDE="ON"
fi
if [ "$COMPILEROVERRIDE" = "ON" ]; then
 CC="$CCDEFAULT"
 CPP="$CPPDEFAULT"
 CXX="$CXXDEFAULT"
 CFLAGS="$CFLAGSBASIC"
 CXXFLAGS="$CXXFLAGSBASIC"
 CPPFLAGS="$CPPFLAGSBASIC"
 RUSTFLAGS="$RUSTFLAGSBASIC"
 LD="$LDMOLD"
 LDFLAGS="$LDFLAGSMOLD"
else
 COMPILEROVERRIDE="OFF"
fi
echo "*** COMPILEROVERRIDE selected is $COMPILEROVERRIDE."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://codeberg.org"
GITREPO="ziglang"
GITTREE="zig"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git cmake \
 llvm-$LLVMVER llvm-$LLVMVER-dev clang-$LLVMVER libclang-$LLVMVER-dev liblld-$LLVMVER-dev
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## VERSION CHECK
if [ -f "$DESTDIR/bin/zig" -a "$GITBRANCH" != "master" ]; then
 echo "*** Checking Version."
 if [ "$GITBRANCH" = "`zig version`" ]; then
  echo "*** PKGVER equal to installed version. Exiting."
  exit
 fi
fi

## CLEAN
sudo rm -Rf "$PKGDIR/.zig-cache"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=100

## CONFIGURE
cmake -DCMAKE_INSTALL_PREFIX="$DESTDIR" -DCMAKE_INSTALL_LIBDIR="$DESTDIR/lib/$MULTILIBDIR" \
-DCMAKE_BUILD_TYPE="$BUILDTYPE" -B tmpbuild -G Ninja

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
