#!/bin/sh

### Package: mix-install-missioncenter
### Version: v0.20250916.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "main".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="main"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## COMPILEROVERRIDE
if [ -z "$COMPILEROVERRIDE" ]; then
 COMPILEROVERRIDE="ON"
fi
if [ "$COMPILEROVERRIDE" = "ON" ]; then
 CC="$CCSTABLE"
 CPP="$CPPSTABLE"
 CXX="$CXXSTABLE"
 CFLAGS="$CFLAGSBASIC"
 CXXFLAGS="$CXXFLAGSBASIC"
 CPPFLAGS="$CPPFLAGSBASIC"
 LD="$LDGOLD"
 LDFLAGS="$LDFLAGSGOLD"
else
 COMPILEROVERRIDE="OFF"
fi
echo "*** COMPILEROVERRIDE selected is $COMPILEROVERRIDE."

## GITPR
if [ -z "$GITPR" ]; then
 GITPR="none"
fi
echo "*** GITPR selected is $GITPR."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://gitlab.com"
GITREPO="mission-center-devs"
GITTREE="mission-center"
PKGDIR="$GITTREE-$GITBRANCH"
GITPRURL="$GITURL"
GITPRPATCH="$GITPRURL/$GITREPO/$GITTREE/-/merge_requests/$GITPR.patch"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git meson \
 blueprint-compiler
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## CLEAN
sudo rm -Rf "$PKGDIR/tmpbuild"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=100

## GITPR
if [ "$GITPR" != "none" ]; then
 rm -f "$DEVDIR/$GITTREE-$GITPR.patch"
 wget "$GITPRPATCH -O $DEVDIR/$GITTREE-$GITPR.patch"
 patch -p1 < "$DEVDIR/$GITTREE-$GITPR.patch"
fi

## CONFIGURE
meson setup tmpbuild --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --buildtype="$BUILDTYPE"

## BUILD
ninja -C tmpbuild

## INSTALL
ninja -C tmpbuild install
sudo ldconfig

## EXIT
echo "*** Done."
exit

# ENJOY
