#!/bin/sh

### Package: mix-install-vapoursynth-editor
### Version: v0.20250928.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
# Upstream branch is "master".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="vs-api4"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## TMPDIR
if [ -z "$TMPDIR" ]; then
 TMPDIR="/tmp/mix-tools"
fi
echo "*** TMPDIR selected is $TMPDIR."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="yomikor"
GITTREE="vapoursynth-editor"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## GIT
[ -d "$PKGDIR" ] || git clone --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

## BUILD
cd pro
qmake6 -norecursive pro.pro CONFIG+=release
make -j `nproc`

## INSTALL
cd ..
sudo install -D -m 755 "build/release-64bit-gcc/vsedit" "$DESTDIR/bin/vsedit"
sudo install -D -m 755 "build/release-64bit-gcc/vsedit-encode" "$DESTDIR/bin/vsedit-encode"
sudo install -D -m 755 "build/release-64bit-gcc/vsedit-job-server" "$DESTDIR/bin/vsedit-job-server"
sudo install -D -m 755 "build/release-64bit-gcc/vsedit-job-server-watcher" "$DESTDIR/bin/vsedit-job-server-watcher"
sudo install -D -m 644 "build/release-64bit-gcc/vsedit.ico" "$DESTDIR/share/vsedit/vsedit.ico"
sudo install -D -m 644 "build/release-64bit-gcc/vsedit.svg" "$DESTDIR/share/vsedit/vsedit.svg"
sudo install -D -m 644 "build/release-64bit-gcc/CHANGELOG" "$DESTDIR/share/doc/vsedit/CHANGELOG"
sudo install -D -m 644 "build/release-64bit-gcc/LICENSE" "$DESTDIR/share/doc/vsedit/LICENSE"
sudo install -D -m 644 "build/release-64bit-gcc/README" "$DESTDIR/share/doc/vsedit/README"
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
