#!/bin/sh

### Package: mix-install-svt-av1-hdr
### Version: v0.20250629.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: dovi hdr10plus

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
# upstream branch is "main"
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="main"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## AVX512
# options are off or on
if [ -z "$AVX512" ]; then
 AVX512="ON"
fi
echo "*** AVX512 selected is $AVX512."

# DOVI
# options are off or on
if [ -z "$DOVI" ]; then
 DOVI="0"
fi
echo "*** DOVI selected is $DOVI."

# HDR10PLUS
# options are off or on
if [ -z "$HDR10PLUS" ]; then
 HDR10PLUS="0"
fi
echo "*** HDR10PLUS selected is $HDR10PLUS."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="juliobbv-p"
GITTREE="svt-av1-hdr"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y build-dep svt-av1
 sudo apt-get -y install build-essential coreutils libc-bin git cmake
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## CLEAN
rm -Rf "$PKGDIR/tmpbuild"

## GIT
[ -d "$PKGDIR" ] || git clone --depth=100 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

## CONFIGURE
cmake -DCMAKE_INSTALL_PREFIX="$DESTDIR" -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_LIBDIR="$DESTDIR/lib/$MULTILIBDIR" \
-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
-DLIBDOVI_FOUND="$DOVI" -DLIBHDR10PLUS_RS_FOUND="$HDR10PLUS" \
-DSVT_AV1_LTO=ON -DENABLE_AVX512="$AVX512" -B tmpbuild -G Ninja

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
