#!/bin/sh

### Package: mix-install-ffmpeg
### Version: v0.20251217.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: svt-hevc, x265, x264, vmaf, lensfun, aribcaption, qrencode, quirc, uavs3d, vvenc

### OVERRIDES

## MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "master", release tags are "n#.#(.#)", branches are "release/#.#".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="release/8.0"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## BUILDCONFIG
# Options are minimal or full
if [ -z "$BUILDCONFIG" ]; then
 BUILDCONFIG="full"
fi
echo "*** BUILDCONFIG selected is $BUILDCONFIG."

## PKGVER
# Options include 7.0, 7.1, 8.0, and master. Default is 8.0.
# VERSIONPARAMS
VERSION60PARAMS=""
VERSION70PARAMS="--enable-libdvdnav --enable-libdvdread --enable-libqrencode --enable-libaribcaption --enable-libharfbuzz"
VERSION71PARAMS="--enable-libvvenc"
VERSION80PARAMS=""
VERSIONMASTERPARAMS="--enable-libsvtjpegxs"
# Default
if [ -z "$PKGVER" ]; then
 PKGVER="8.0"
fi
# 6.0
if [ "$PKGVER" = "6.0" ];  then
 VERSIONPARAMS="$VERSION60PARAMS"
fi
# 7.0
if [ "$PKGVER" = "7.0" ];  then
 VERSIONPARAMS="$VERSION60PARAMS $VERSION70PARAMS"
fi
# 7.1
if [ "$PKGVER" = "7.1" ];  then
 VERSIONPARAMS="$VERSION60PARAMS $VERSION70PARAMS $VERSION71PARAMS"
fi
# 8.0
if [ "$PKGVER" = "8.0" ];  then
 VERSIONPARAMS="$VERSION60PARAMS $VERSION70PARAMS $VERSION71PARAMS $VERSION80PARAMS"
fi
# master
if [ "$PKGVER" = "master" ];  then
 VERSIONPARAMS="$VERSION60PARAMS $VERSION70PARAMS $VERSION71PARAMS $VERSION80PARAMS $VERSIONMASTERPARAMS"
fi
echo "*** PKGVER selected is $PKGVER."

## SVTAV1PSY
if [ -z "$SVTAV1PSY" ]; then
 SVTAV1PSY="ON"
fi
echo "*** SVTAV1PSY selected is $SVTAV1PSY."

## AV1VULKANENCODER
if [ -z "$AV1VULKANENCODER" ]; then
 AV1VULKANENCODER="OFF"
fi
echo "*** AV1VULKANENCODER selected is $AV1VULKANENCODER."

## VARS
DATE="`date +%Y%m%d%H%M%S`"
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="ffmpeg"
GITTREE="ffmpeg"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## DEPS
# Provide INSTALLDEPS=debian to install dependencies.
if [ "$INSTALLDEPS" = "debian" ]; then
  sudo apt-get -y build-dep ffmpeg
  sudo apt-get -y install build-essential coreutils libc-bin wget tar bzip2 patch make \
  libudev-dev libdrm-dev libvpl-dev liblc3-dev libqrencode-dev libssh-dev libtls-dev \
  libpocketsphinx-dev
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=1000 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard HEAD
git pull
git submodule update --init --depth=1000

## PATCH
# Support SVT-AV1-PSY Extended CRF
if [ "$SVTAV1PSY" = "ON" ]; then
 echo "*** PATCHING ffmpeg for SVT-AV1-PSY extended CRF for version 7.1+."
 if [ "$PKGVER" = "7.1" ]; then
  patch -p1 < "$RESDIR/ffmpeg/ffmpeg_svt-av1-psy_extended-crf_7.1.patch"
 fi
 if [ "$PKGVER" = "8.0" ]; then
  patch -p1 < "$RESDIR/ffmpeg/ffmpeg_svt-av1-psy_extended-crf_master.patch"
 fi
fi

# Support av1_vulkan encoder
if [ "$AV1VULKANENCODER" = "ON" ]; then
  if [ "$PKGVER" = "7.1" ]; then
   echo "*** PATCHING ffmpeg for av1_vulkan encoder."
   patch -p1 < "$RESDIR/ffmpeg/ffmpeg-av1_vulkan_encoder_patch_v3_01.patch"
   patch -p1 < "$RESDIR/ffmpeg/ffmpeg-av1_vulkan_encoder_patch_v3_02.patch"
  fi
fi

## CONFIGURE
# options are minimal and full
if [ "$BUILDCONFIG" = "minimal" ]; then
 echo "*** BUILDCONFIG selected is $BUILDCONFIG."
 ./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --shlibdir="$DESTDIR/lib/$MULTILIBDIR" \
 --enable-gpl --enable-version3 --enable-nonfree  --enable-shared --enable-pic --disable-debug \
 --enable-lto --cc="$CC" --cxx="$CXX" --extra-cflags="$CFLAGS" --extra-cxxflags="$CXXFLAGS" \
 --disable-doc
fi
if [ "$BUILDCONFIG" = "full" ]; then
 echo "\n*** Using full BUILDCONFIG.\n"
 ./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" --shlibdir="$DESTDIR/lib/$MULTILIBDIR" \
 --enable-gpl --enable-version3 --enable-nonfree  --enable-shared --enable-pic --disable-debug \
 --enable-lto --cc="$CC" --cxx="$CXX" --extra-cflags="$CFLAGS" --extra-cxxflags="$CXXFLAGS" \
 --enable-chromaprint --enable-frei0r --enable-gcrypt --enable-gmp --enable-gnutls \
 --enable-ladspa --enable-lcms2 --enable-libaom --enable-libaribb24 \
 --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca \
 --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdavs2 --enable-libdc1394 \
 --enable-libfdk-aac --enable-libflite --enable-libfontconfig \
 --enable-libfreetype --enable-libfribidi --enable-libgme \
 --enable-libgsm --enable-libiec61883 --enable-libilbc --enable-libjack --enable-libjxl \
 --enable-libklvanc --enable-libkvazaar --enable-liblc3 --enable-liblensfun \
 --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb \
 --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt \
 --enable-libopus --enable-libplacebo --enable-libpulse \
 --enable-librabbitmq --enable-librav1e --enable-librist --enable-librsvg \
 --enable-librist --enable-librsvg --enable-librubberband --enable-librtmp --enable-libshaderc \
 --enable-libshine --enable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex \
 --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract \
 --enable-libtheora --enable-libtls --enable-libtwolame --enable-libuavs3d \
 --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis \
 --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 \
 --enable-libxavs2 --enable-libxcb \
 --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-libxvid --enable-libxml2 \
 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 \
 --enable-libmysofa --enable-openal --enable-opencl --enable-opengl \
 --enable-vapoursynth --enable-libvpl $VERSIONPARAMS
fi

# --enable-pocketsphinx

## Not Selected
# Discontinued: libcelt
# Alternative: openssl, mbedtls, glslang, mfx, xavs

## TODO:
# jni libcelt liblcevc-dec libopencv libopenvino libqrencode libquirc libtensorflow libtorch
# libvvenc libxeve libxexd libxavs
# decklink mbedtls mediacodec mediafoundation openssl mfx npp mmal omx

## BUILD
make -j `nproc`

## INSTALL
sudo make install
sudo ldconfig

## EXIT
echo "*** Done."
exit

## ENJOY
