#!/bin/sh

### Package: mix-config-snapper
### Version: v0.20250629.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### VARIABLES

## DATE
DATE="`date +%Y%m%d%H%M%S`"

## SNAPSHOTROOT
# Options are enabled or disabled
if [ -z "$SNAPSHOTROOT" ]; then
 SNAPSHOTROOT="enabled"
fi
echo "*** SNAPSHOTROOT is $SNAPSHOTROOT."

## SNAPSHOTHOME
# Options are enabled or disabled
if [ -z "$SNAPSHOTHOME" ]; then
 SNAPSHOTHOME="enabled"
fi
echo "*** SNAPSHOTHOME is $SNAPSHOTHOME."

## ENV
set -e

## PROCESS ROOT
if [ "$SNAPSHOTROOT" = "enabled" ]; then
 echo "*** Processing / (root) snapper config."
 ## SNAPPER
 if [ ! -f "/etc/snapper/configs/root" ]; then
  if [ -d "/.snapshots" ]; then
   sudo mv "/.snapshots" "/.snapshots.bak-$DATE"
  fi
  sudo snapper -c root create-config /

  ## CONFIGURE
  sudo snapper -c root set-config TIMELINE_LIMIT_HOURLY="24"
  sudo snapper -c root set-config TIMELINE_LIMIT_DAILY="7"
  sudo snapper -c root set-config TIMELINE_LIMIT_WEEKLY="4"
  sudo snapper -c root set-config TIMELINE_LIMIT_MONTHLY="12"
  sudo snapper -c root set-config TIMELINE_LIMIT_QUARTERLY="0"
  sudo snapper -c root set-config TIMELINE_LIMIT_YEARLY="7"
 else
  echo "*** SNAPSHOTROOT configuration already exists. Skipping."
 fi
fi

## PROCESS HOME
if [ "$SNAPSHOTHOME" = "enabled" ]; then
 echo "*** Processing /home snapper config."
 # SNAPPER
 if [ ! -f "/etc/snapper/configs/home" ]; then
  if [ -d "/home/.snapshots" ]; then
   sudo mv "/home/.snapshots" "/home/.snapshots.bak-$DATE"
  fi
  sudo snapper -c home create-config /home

  ## CONFIGURE

  sudo snapper -c home set-config TIMELINE_LIMIT_HOURLY="24"
  sudo snapper -c home set-config TIMELINE_LIMIT_DAILY="7"
  sudo snapper -c home set-config TIMELINE_LIMIT_WEEKLY="4"
  sudo snapper -c home set-config TIMELINE_LIMIT_MONTHLY="12"
  sudo snapper -c home set-config TIMELINE_LIMIT_QUARTERLY="0"
  sudo snapper -c home set-config TIMELINE_LIMIT_YEARLY="7"
 else
  echo "*** SNAPSHOTHOME configuration already exists. Skipping."
 fi
fi

## ENABLE TIMERS
echo "*** Enabling systemctl timers."
sudo systemctl daemon-reload
sudo systemctl enable --now snapper-timeline.timer
sudo systemctl enable --now snapper-cleanup.timer

## RESTART SERVICE
echo "*** Restarting snapperd service."
sudo systemctl restart --now snapperd.service
sudo systemctl start --now snapper-timeline.timer
sudo systemctl start --now snapper-cleanup.timer


## EXIT
echo "*** Done."
exit

## ENJOY
