#!/bin/sh

### Package: mix-install-tsmuxer
### Version: v0.20250629.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
# Upstream is "master". Releases are "#.#".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="2.7.0"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## TMPDIR
if [ -z "$TMPDIR" ]; then
 TMPDIR="/tmp/mix-tools"
fi
echo "*** TMPDIR selected is $TMPDIR."

## COMPILER
# Does not work with ccache.
CC="gcc"
CXX="g++"
CPP="g++ -E"

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="justdan96"
GITTREE="tsmuxer"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y install build-essential coreutils libc-bin git
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## GIT
[ -d "$PKGDIR" ] || git clone --depth=1 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

## TMPDIR
rm -Rf "$TMPDIR/$PKGDIR"
mkdir -p "$TMPDIR"
cp -R "$DEVDIR/$PKGDIR" "$TMPDIR/"
cd "$TMPDIR/$PKGDIR"

## CONFIGURE
cmake -DCMAKE_INSTALL_PREFIX="$DESTDIR" -DCMAKE_INSTALL_LIBDIR="$DESTDIR/lib/$MULTILIBDIR" \
-DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
-DTSMUXER_GUI=ON -B ./tmpbuild -G Ninja

## BUILD
ninja -C tmpbuild

## INSTALL
sudo ninja -C tmpbuild install
sudo ldconfig

## EXIT
exit

## ENJOY
