#! /bin/sh

### Package: mix-install-task-ffmpeg
### Version: v20240728.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z $MIXTOOLSDIR ]; then
 export MIXTOOLSDIR=~/Development/XMIXAHLX/mix-tools
 export PATH=$MIXTOOLSDIR:$PATH
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

# SVTAV1VER
# override with anything else to select official
if [ -z $SVTAV1VER ]; then
 SVTAV1VER=PSY
fi
echo "*** SVTAV1VER selected is $SVTAV1VER."

## INSTALL
mix-install-amf
mix-install-dav1d
mix-install-libdvbcsa
mix-install-libdca
mix-install-libmpeg2
mix-install-libbdplus
mix-install-libudfread
#mix-install-liba52
mix-install-libaacs
mix-install-libbluray
mix-install-libdvdnav
mix-install-libdvdread
mix-install-libdvdcss
mix-install-lensfun
mix-install-vmaf
mix-install-ogg
mix-install-vorbis
mix-install-vorbis-tools
mix-install-opus
mix-install-libopusenc
mix-install-opusfile
mix-install-opus-tools
mix-install-quirc
mix-install-speex
mix-install-uavs3d
mix-install-libaribcaption
mix-install-libplacebo
mix-install-zimg
mix-install-svt-hevc
# SVTAV1VER
if [ $SVTAV1VER = PSY ];then
 mix-install-dovi
 mix-install-hdr10plus
 mix-install-svt-av1-psy
 else
 mix-install-svt-av1
fi
mix-install-x264
mix-install-x265
mix-install-ffmpeg

## EXIT
exit

## ENJOY
