#!/bin/sh

### Package: mix-install-libnvme
### Version: v0.20250629.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi
echo "*** INSTALLDEPS selected is $INSTALLDEPS."

## GITBRANCH
# Upstream branch is "master". Releases are tagged "v#.#".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="master"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr"
fi
echo "*** DESTDIR selected is $DESTDIR."

## SYSCONFDIR
# local
if [ "$DESTDIR" = "/usr/local" ]; then
 SYSCONFDIR="/usr/local/etc"
fi
# system
if [ "$DESTDIR" = "/usr" ]; then
 SYSCONFDIR="/etc"
fi
if [ -z "$SYSCONFDIR" ]; then
 SYSCONFDIR="/etc"
fi
echo "*** SYSCONFDIR selected is $SYSCONFDIR."

## TMPDIR
if [ -z "$TMPDIR" ]; then
 TMPDIR="/tmp/mix-tools"
fi
echo "*** TMPDIR selected is $TMPDIR."

## BUILDTYPE
if [ -z "$BUILDTYPE" ]; then
 BUILDTYPE="release"
fi
echo "*** BUILDTYPE selected is $BUILDTYPE."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://github.com"
GITREPO="linux-nvme"
GITTREE="libnvme"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y build-dep libnvme1t64 libnvme-dev
 sudo apt-get -y install build-essential coreutils libc-bin git meson ninja-build \
 liburing-dev libdbus-1-dev
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## GIT
[ -d "$PKGDIR" ] || git clone --recursive --depth=1 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init --recursive --depth=1

## TMPDIR
rm -Rf "$TMPDIR/$PKGDIR"
mkdir -p "$TMPDIR"
cp -R "$DEVDIR/$PKGDIR" "$TMPDIR/"
cd "$TMPDIR/$PKGDIR"

## CONFIGURE
meson setup "$TMPDIR/$PKGDIR/tmpbuild" --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR" \
--sysconfdir="$SYSCONFDIR" --buildtype="$BUILDTYPE" -Dlibdbus="enabled" -Dliburing="enabled"

## BUILD
ninja -C "$TMPDIR/$PKGDIR/tmpbuild"

## INSTALL
sudo ninja -C "$TMPDIR/$PKGDIR/tmpbuild" install
sudo ldconfig

## APT-MARK HOLD
if [ "$INSTALLDEPS" = "debian" ] && [ "$DESTDIR" = "/usr" ]; then
 sudo apt-mark hold libnvme1t64 libnvme-dev
fi

## EXIT
echo "*** Done."
exit

## ENJOY
