#! /bin/sh

### Package: mix-install-task-sway
### Version: v0.20251120.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## OVERRIDES
# MIXTOOLSDIR
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
 PATH="$MIXTOOLSDIR:$PATH"
fi
echo "*** MIXTOOLSDIR selected is $MIXTOOLSDIR."

## INSTALL
mix-install-fontawesome
mix-install-sway
mix-install-swaybg
mix-install-swayidle
mix-install-swaylock

## EXIT
echo "*** Done."
exit

## ENJOY
