#!/bin/sh

### Package: mix-install-mkvtoolnix
### Version: v0.20250729.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

### OVERRIDES

## MIXTOOLS
if [ -z "$MIXTOOLSDIR" ]; then
 MIXTOOLSDIR="`pwd`"
fi

## INSTALLDEPS
if [ -z "$INSTALLDEPS" ]; then
 INSTALLDEPS="debian"
fi

## GITBRANCH
# Upstream is "main". Releases are "release-#.#".
if [ -z "$GITBRANCH" ]; then
 GITBRANCH="main"
fi
echo "*** GITBRANCH selected is $GITBRANCH."

## DESTDIR
if [ -z "$DESTDIR" ]; then
 DESTDIR="/usr/local"
fi
echo "*** DESTDIR selected is $DESTDIR."

## TMPDIR
if [ -z "$TMPDIR" ]; then
 TMPDIR="/tmp/mix-tools"
fi
echo "*** TMPDIR selected is $TMPDIR."

## VARS
RESDIR="$MIXTOOLSDIR/resources"
DEVDIR="$MIXTOOLSDIR/upstream"
GITURL="https://codeberg.org"
GITREPO="mbunkus"
GITTREE="mkvtoolnix"
PKGDIR="$GITTREE-$GITBRANCH"
MULTILIBDIR="`gcc -dumpmachine`"

## INSTALLDEPS
# Debian Dependencies
if [ "$INSTALLDEPS" = "debian" ]; then
 sudo apt-get -y build-dep mkvtoolnix
 sudo apt-get -y install build-essential coreutils libc-bin git \
 pandoc
fi

## PREP
set -e
mkdir -p "$DEVDIR"
cd "$DEVDIR"

## GIT
[ -d "$PKGDIR" ] || git clone --depth=1 "$GITURL/$GITREPO/$GITTREE.git" --branch="$GITBRANCH" "$PKGDIR"
cd "$PKGDIR"
git clean -dfx
git reset --hard
git pull
git submodule update --init

## TMPDIR
rm -Rf "$TMPDIR/$PKGDIR"
mkdir -p "$TMPDIR"
cp -R "$DEVDIR/$PKGDIR" "$TMPDIR/"
cd "$TMPDIR/$PKGDIR"

## CONFIGURE
./autogen.sh
./configure --prefix="$DESTDIR" --libdir="$DESTDIR/lib/$MULTILIBDIR"
# \
#--with-extra-includes="$DESTDIR/include/ebml" \
#--with-extra-libs="$DESTDIR/lib/$MULTILIBDIR"


## BUILD
rake

## INSTALL
sudo rake install
sudo ldconfig

## EXIT
exit

## ENJOY
