#!/bin/bash

### File: mix-resources-configure-autotools
### Version: v20241230.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## CONFIGURE
echo "*** Configuring package with autotools."
# autogen.sh
if [ -f ./autogen.sh" ]; then
 ./autogen.sh
else
 # autoreconf
 autoreconf -vifs
fi
# configure
./configure --prefix="$DESTDIR" --libdir="$DESTDIR"/lib/"$MULTILIBDIR"
