#!/bin/bash

### File: mix-resources-build-make
### Version: v20241230.2300
### Author: Michael Gan "xmixahlx" michaelbgan@gmail.com
### License: GPLv3
### Script Dependencies: (none)

## BUILD MAKE
echo "*** Building package with make."
make -j `nproc`
